import { Link, router } from '@inertiajs/react';
import { ArrowLeft } from 'lucide-react';
import { useState } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import CrudDialog from '@/Components/CrudDialog';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';
import { money } from '@/lib/utils';

const absenceFields = [{ name: 'absence_date', label: 'Date', type: 'date' }, { name: 'status', label: 'Statut', type: 'select', options: [{ value: 'justified', label: 'Justifiée' }, { value: 'unjustified', label: 'Non justifiée' }, { value: 'leave', label: 'Congé' }] }, { name: 'note', label: 'Note', type: 'textarea' }];
export default function Show({ employee, month, calendar }) {
    const [selectedDate, setSelectedDate] = useState(null);
    return <AppLayout title={`RH — ${employee.name}`} actions={<><Link href={route('employees.index')}><Button variant="outline"><ArrowLeft className="h-4 w-4" />Retour aux employés</Button></Link><Link href={route('employees.absences.index', employee.id)}><Button variant="outline">Absences</Button></Link><Link href={route('employees.payments.index', employee.id)}><Button variant="outline">Historique des paiements</Button></Link><CrudDialog title="Payer un employé" action={route('employees.salary-payments.store', employee.id)} fields={[{ name: 'type', label: 'Type de paiement', type: 'select', options: [{ value: 'salary', label: 'Salaire mensuel' }, { value: 'advance', label: 'Avance sur salaire' }, { value: 'bonus', label: 'Prime / bonus' }] }, { name: 'month', label: 'Mois concerné', type: 'month' }, { name: 'payment_date', label: 'Date de paiement', type: 'date' }, { name: 'amount', label: 'Montant DH', type: 'number' }, { name: 'note', label: 'Note', type: 'textarea' }]} defaults={{ type: 'salary', month, payment_date: '', amount: employee.salary, note: '' }} trigger={<Button>Payer / Avance / Prime</Button>} /></>}>
        <div className="mb-5 grid gap-3 md:grid-cols-4"><Card><CardContent><div className="text-sm text-zinc-500">Salaire mensuel</div><div className="mt-1 text-xl font-semibold">{money(employee.salary)}</div></CardContent></Card><Card><CardContent><div className="text-sm text-zinc-500">Paiement prévu</div><div className="mt-1 text-xl font-semibold">Le {employee.salary_payment_day} de chaque mois</div></CardContent></Card><Card><CardContent><div className="text-sm text-zinc-500">Téléphone</div><div className="mt-1 font-semibold">{employee.telephone || '-'}</div></CardContent></Card><Card><CardContent><div className="text-sm text-zinc-500">Statut</div><div className="mt-1 font-semibold">{employee.status === 'active' ? 'Actif' : 'Inactif'}</div></CardContent></Card></div>
        <Card className="mb-5"><CardContent><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><div className="font-semibold">Work calendar</div><div className="text-sm text-zinc-500">Select a day, then mark it as Work or Day off.</div></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded bg-emerald-500 px-2 py-1 text-white">Work</span><span className="rounded bg-red-500 px-2 py-1 text-white">Absent</span><span className="rounded bg-amber-100 px-2 py-1">Scheduled</span><span className="rounded bg-zinc-100 px-2 py-1">Off</span></div></div><div className="mb-3 flex gap-2"><Input type="month" value={month} onChange={(e) => router.get(route('employees.show', employee.id), { month: e.target.value })} /><CrudDialog title="Ajouter une absence" action={route('employees.absences.store', employee.id)} fields={absenceFields} defaults={{ absence_date: '', status: 'unjustified', note: '' }} trigger={<Button variant="outline">Absence</Button>} /></div><div className="grid grid-cols-7 gap-2">{calendar.map((day) => <button key={day.date} type="button" onClick={() => setSelectedDate(day.date)} className={`rounded p-2 text-sm ${selectedDate === day.date ? 'ring-2 ring-violet-700' : ''} ${day.status === 'worked' ? 'bg-emerald-500 text-white' : day.status === 'absent' ? 'bg-red-500 text-white' : day.status === 'scheduled' ? 'bg-amber-100' : 'bg-zinc-100 text-zinc-400'}`}><div className="font-semibold">{day.day}</div><div className="text-[10px]">{day.status === 'worked' ? 'Work' : day.status === 'absent' ? 'Absent' : day.status === 'scheduled' ? 'Scheduled' : 'Off'}</div></button>)}</div>{selectedDate ? <div className="mt-4 flex flex-wrap items-center gap-2 rounded-md bg-violet-50 p-3"><span className="text-sm font-medium">Selected: {selectedDate}</span><Button size="sm" onClick={() => router.post(route('employees.work-days.store', employee.id), { work_date: selectedDate, status: 'worked' })}>Mark Work</Button><Button size="sm" variant="outline" onClick={() => router.post(route('employees.work-days.store', employee.id), { work_date: selectedDate, status: 'off' })}>Day off</Button></div> : null}</CardContent></Card>
    </AppLayout>;
}
