const SECTION_THEMES = {
    dashboard: {
        key: 'dashboard',
        icon: 'text-slate-600',
        title: 'text-slate-800',
        header: 'border-slate-300',
        content: 'border-slate-500',
        sidebarGroup: 'bg-slate-100 text-slate-800 hover:bg-slate-200 hover:text-slate-900',
        sidebarChild: 'bg-slate-200 text-slate-950 hover:bg-slate-200 hover:text-slate-950',
        sidebarDivider: 'border-slate-200',
        sidebarIdle: 'bg-slate-100 text-slate-900 hover:bg-slate-200',
        sidebarActive: 'bg-slate-300 text-slate-950 ring-1 ring-slate-400',
        sidebarChildIdle: 'bg-slate-50 text-slate-800 hover:bg-slate-100',
    },
    depot: {
        key: 'depot',
        icon: 'text-emerald-600',
        title: 'text-emerald-800',
        header: 'border-emerald-300',
        content: 'border-emerald-500',
        sidebarGroup: 'bg-emerald-50 text-emerald-800 hover:bg-emerald-100 hover:text-emerald-900',
        sidebarChild: 'bg-emerald-100 text-emerald-950 hover:bg-emerald-100 hover:text-emerald-950',
        sidebarDivider: 'border-emerald-200',
        sidebarIdle: 'bg-emerald-100 text-emerald-900 hover:bg-emerald-200',
        sidebarActive: 'bg-emerald-300 text-emerald-950 ring-1 ring-emerald-400',
        sidebarChildIdle: 'bg-emerald-50 text-emerald-800 hover:bg-emerald-100',
    },
    fournisseurs: {
        key: 'fournisseurs',
        icon: 'text-amber-600',
        title: 'text-amber-800',
        header: 'border-amber-300',
        content: 'border-amber-500',
        sidebarGroup: 'bg-amber-50 text-amber-800 hover:bg-amber-100 hover:text-amber-900',
        sidebarChild: 'bg-amber-100 text-amber-950 hover:bg-amber-100 hover:text-amber-950',
        sidebarDivider: 'border-amber-200',
        sidebarIdle: 'bg-amber-100 text-amber-900 hover:bg-amber-200',
        sidebarActive: 'bg-amber-300 text-amber-950 ring-1 ring-amber-400',
        sidebarChildIdle: 'bg-amber-50 text-amber-800 hover:bg-amber-100',
    },
    clients: {
        key: 'clients',
        icon: 'text-blue-600',
        title: 'text-blue-800',
        header: 'border-blue-300',
        content: 'border-blue-500',
        sidebarGroup: 'bg-blue-50 text-blue-800 hover:bg-blue-100 hover:text-blue-900',
        sidebarChild: 'bg-blue-100 text-blue-950 hover:bg-blue-100 hover:text-blue-950',
        sidebarDivider: 'border-blue-200',
        sidebarIdle: 'bg-blue-100 text-blue-900 hover:bg-blue-200',
        sidebarActive: 'bg-blue-300 text-blue-950 ring-1 ring-blue-400',
        sidebarChildIdle: 'bg-blue-50 text-blue-800 hover:bg-blue-100',
    },
    cheques: {
        key: 'cheques',
        icon: 'text-fuchsia-600',
        title: 'text-fuchsia-800',
        header: 'border-fuchsia-300',
        content: 'border-fuchsia-500',
        sidebarGroup: 'bg-fuchsia-50 text-fuchsia-800 hover:bg-fuchsia-100 hover:text-fuchsia-900',
        sidebarChild: 'bg-fuchsia-100 text-fuchsia-950 hover:bg-fuchsia-100 hover:text-fuchsia-950',
        sidebarDivider: 'border-fuchsia-200',
        sidebarIdle: 'bg-fuchsia-100 text-fuchsia-900 hover:bg-fuchsia-200',
        sidebarActive: 'bg-fuchsia-300 text-fuchsia-950 ring-1 ring-fuchsia-400',
        sidebarChildIdle: 'bg-fuchsia-50 text-fuchsia-800 hover:bg-fuchsia-100',
    },
    caisse: {
        key: 'caisse',
        icon: 'text-cyan-600',
        title: 'text-cyan-800',
        header: 'border-cyan-300',
        content: 'border-cyan-500',
        sidebarGroup: 'bg-cyan-50 text-cyan-800 hover:bg-cyan-100 hover:text-cyan-900',
        sidebarChild: 'bg-cyan-100 text-cyan-950 hover:bg-cyan-100 hover:text-cyan-950',
        sidebarDivider: 'border-cyan-200',
        sidebarIdle: 'bg-cyan-100 text-cyan-900 hover:bg-cyan-200',
        sidebarActive: 'bg-cyan-300 text-cyan-950 ring-1 ring-cyan-400',
        sidebarChildIdle: 'bg-cyan-50 text-cyan-800 hover:bg-cyan-100',
    },
    employees: {
        key: 'employees',
        icon: 'text-violet-600',
        title: 'text-violet-800',
        header: 'border-violet-300',
        content: 'border-violet-500',
        sidebarGroup: 'bg-violet-50 text-violet-800 hover:bg-violet-100 hover:text-violet-900',
        sidebarChild: 'bg-violet-100 text-violet-950 hover:bg-violet-100 hover:text-violet-950',
        sidebarDivider: 'border-violet-200',
        sidebarIdle: 'bg-violet-100 text-violet-900 hover:bg-violet-200',
        sidebarActive: 'bg-violet-300 text-violet-950 ring-1 ring-violet-400',
        sidebarChildIdle: 'bg-violet-50 text-violet-800 hover:bg-violet-100',
    },
    users: {
        key: 'users',
        icon: 'text-rose-600',
        title: 'text-rose-800',
        header: 'border-rose-300',
        content: 'border-rose-500',
        sidebarGroup: 'bg-rose-50 text-rose-800 hover:bg-rose-100 hover:text-rose-900',
        sidebarChild: 'bg-rose-100 text-rose-950 hover:bg-rose-100 hover:text-rose-950',
        sidebarDivider: 'border-rose-200',
        sidebarIdle: 'bg-rose-100 text-rose-900 hover:bg-rose-200',
        sidebarActive: 'bg-rose-300 text-rose-950 ring-1 ring-rose-400',
        sidebarChildIdle: 'bg-rose-50 text-rose-800 hover:bg-rose-100',
    },
    history: {
        key: 'history',
        icon: 'text-lime-600',
        title: 'text-lime-800',
        header: 'border-lime-300',
        content: 'border-lime-500',
        sidebarGroup: 'bg-lime-50 text-lime-800 hover:bg-lime-100 hover:text-lime-900',
        sidebarChild: 'bg-lime-100 text-lime-950 hover:bg-lime-100 hover:text-lime-950',
        sidebarDivider: 'border-lime-200',
        sidebarIdle: 'bg-lime-100 text-lime-900 hover:bg-lime-200',
        sidebarActive: 'bg-lime-300 text-lime-950 ring-1 ring-lime-400',
        sidebarChildIdle: 'bg-lime-50 text-lime-800 hover:bg-lime-100',
    },
};

const ROUTE_PREFIXES = {
    dashboard: ['dashboard'],
    depot: ['depots.', 'articles.', 'operations.', 'devis.', 'livraisons.', 'groupes.'],
    fournisseurs: ['fournisseurs.'],
    clients: ['clients.'],
    cheques: ['cheques.'],
    caisse: ['caisse.'],
    employees: ['employees.'],
    users: ['users.'],
    history: ['activity-history.'],
};

export function getSectionThemeByKey(key) {
    return key ? SECTION_THEMES[key] || null : null;
}

export function getSectionTheme(routeName) {
    const key = Object.entries(ROUTE_PREFIXES).find(([, prefixes]) => prefixes.some((prefix) => routeName?.startsWith(prefix)))?.[0];
    return getSectionThemeByKey(key);
}
